name: CI
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    strategy:
      matrix:
        build: [linux, mac, windows]
        include:
          - build: linux
            os: ubuntu-latest
          - build: mac
            os: macos-latest
          - build: windows
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install rust
        uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
      - run: cargo test
